// @vitest-environment node
import { beforeEach, expect, it, vi } from 'vitest';
import sharp from 'sharp';
vi.mock('server-only',()=>({}));
const state=vi.hoisted(()=>({role:'super_admin',version:2,path:'',objects:new Set<string>(),events:[] as string[],fail:false,ambiguous:false,cleanupFail:false,readFail:false,networkBeforeCommit:false}));
vi.mock('@/lib/auth',()=>({requireAdmin:async()=>{if(state.role!=='super_admin')throw new Error('denied');return {username:'admin',name:'مدير النظام'};}}));
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:()=>({
 from:()=>({select:()=>({eq:()=>({abortSignal:()=>({single:async()=>({data:{id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',version:state.version,image_path:state.path,archived_at:null},error:state.readFail && state.events.includes('commit')?{code:'network'}:null})})})})}),
 storage:{from:()=>({upload:async(key:string)=>{state.events.push('upload');state.objects.add(key);return {error:null};},remove:async(keys:string[])=>{state.events.push('delete');if(state.cleanupFail)return {error:{message:'unavailable'}};keys.forEach(k=>state.objects.delete(k));return {error:null};}})},
 rpc:(_name:string,p:{p_image_path:string|null})=>({abortSignal:async()=>{state.events.push('commit');if(state.networkBeforeCommit)throw new Error('network');if(state.fail)return {data:null,error:{code:'PT409'}};state.path=p.p_image_path??'';state.version++;if(state.ambiguous)throw new Error('network');return {error:null,data:{id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',version:state.version,image:p.p_image_path,updatedAt:'now'}};}}),
})}));
import { runImageCommand } from '@/lib/admin/images/command';
const id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const oldKey=`programs/${id}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.png`;
async function file(){const b=await sharp({create:{width:2,height:2,channels:3,background:'blue'}}).png().toBuffer();return new File([new Uint8Array(b)],'untrusted.png',{type:'image/png'});}
beforeEach(()=>{state.role='super_admin';state.version=2;state.path='/api/program-images/'+oldKey.slice(9);state.objects=new Set([oldKey]);state.events=[];state.fail=false;state.ambiguous=false;state.cleanupFail=false;state.readFail=false;state.networkBeforeCommit=false;vi.restoreAllMocks();vi.stubEnv('ADMIN_DATA_SOURCE','supabase');});
it('uploads then commits then deletes old owned object',async()=>{const r=await runImageCommand({id,expectedVersion:2,action:'upload',file:await file()});expect(state.events).toEqual(['upload','commit','delete']);expect(state.objects.has(oldKey)).toBe(false);expect(state.objects.size).toBe(1);expect(r.version).toBe(3);});
it('compensates a rejected metadata update without deleting the old object',async()=>{state.fail=true;await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toMatchObject({reason:'conflict'});expect([...state.objects]).toEqual([oldKey]);expect(state.path).toContain('aaaaaaaa');});
it('does not delete an object after an ambiguous commit that actually succeeded',async()=>{state.ambiguous=true;vi.spyOn(console,'error').mockImplementation(()=>{});await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toThrow();expect(state.objects.has('programs/'+state.path.slice('/api/program-images/'.length))).toBe(true);expect(state.objects.size).toBe(2);});
it('removes the DB reference before deleting and never deletes local assets',async()=>{await runImageCommand({id,expectedVersion:2,action:'remove'});expect(state.events).toEqual(['commit','delete']);expect(state.objects.size).toBe(0);state.path='/images/local.jpg';state.events=[];await runImageCommand({id,expectedVersion:3,action:'remove'});expect(state.path).toBe('');expect(state.events).toEqual(['commit']);});
it('denies staff and stale versions before uploading',async()=>{state.role='staff';await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toThrow('denied');state.role='super_admin';await expect(runImageCommand({id,expectedVersion:1,action:'upload',file:await file()})).rejects.toMatchObject({reason:'conflict'});expect(state.events).toEqual([]);});

it('reports old object cleanup failure without undoing the saved reference',async()=>{state.cleanupFail=true;const log=vi.spyOn(console,'error').mockImplementation(()=>{});const r=await runImageCommand({id,expectedVersion:2,action:'upload',file:await file()});expect(r.cleanupPending).toBe(true);expect(state.version).toBe(3);expect(state.path).toBe(r.image);expect(state.objects.size).toBe(2);expect(log).toHaveBeenCalledWith('SSTLI_IMAGE_CLEANUP_REQUIRED');});
it('retains the new object and reports reconciliation when rereading an uncertain commit fails',async()=>{state.fail=true;state.readFail=true;const log=vi.spyOn(console,'error').mockImplementation(()=>{});await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toMatchObject({reason:'conflict'});expect(state.objects.size).toBe(2);expect(log).toHaveBeenCalledWith('SSTLI_IMAGE_RECONCILIATION_REQUIRED');});
it('reports failed compensation while preserving the previous reference',async()=>{state.fail=true;state.cleanupFail=true;const log=vi.spyOn(console,'error').mockImplementation(()=>{});await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toMatchObject({reason:'conflict'});expect(state.path).toContain('aaaaaaaa');expect(state.objects.size).toBe(2);expect(log).toHaveBeenCalledWith('SSTLI_IMAGE_CLEANUP_REQUIRED');});

it('retains an uploaded object after a transport failure even when a reread could still show the old reference',async()=>{state.networkBeforeCommit=true;const log=vi.spyOn(console,'error').mockImplementation(()=>{});await expect(runImageCommand({id,expectedVersion:2,action:'upload',file:await file()})).rejects.toThrow('network');expect(state.objects.size).toBe(2);expect(state.events).toEqual(['upload','commit']);expect(log).toHaveBeenCalledWith('SSTLI_IMAGE_RECONCILIATION_REQUIRED');});
