"use client";
import { useState } from 'react';
import Link from 'next/link';
import { History } from 'lucide-react';
import type { AdminActivity } from '@/lib/admin/types';
import { actionLabels, entityLabels, sampleActivity } from '@/lib/admin/mock-data';
import { normalizeSearch } from '@/lib/filters';
import { useAdmin } from './AdminProvider';
import { EmptyState, PageHeader, SearchField } from './ui';
import { FilterSelect, Modified, Pagination } from './DataView';

export function ActivityRows({ items, compact = false }: { items: AdminActivity[]; compact?: boolean }) {
  return <ol className="adm-timeline">{items.map(item => <li key={item.id}><span className="adm-timeline-icon"><History size={17} /></span><div className="adm-timeline-content"><div className="adm-timeline-title"><strong>{actionLabels[item.action]} · {item.title}</strong><span className={`adm-badge ${item.sample ? 'adm-example' : 'adm-active'}`}>{item.sample ? 'مثال' : 'هذه الجلسة'}</span></div><p>{item.actor} · {entityLabels[item.entityType]} · <Modified time={item.time} /></p>{!compact && <details className="adm-change-details"><summary>عرض التغييرات ({item.changes.length})</summary><div className="adm-change-grid"><span>الحقل</span><span>قبل</span><span>بعد</span>{item.changes.map((change, index) => <div className="adm-change-row" key={index}><strong>{change.field}</strong><span><small>قبل</small>{change.before}</span><span><small>بعد</small>{change.after}</span></div>)}</div>{!item.sample && (item.programId || item.entityType === 'branch') && <Link className="adm-text-link" href={item.entityType === 'branch' ? `/admin/branches/${encodeURIComponent(item.entityId)}` : `/admin/programs/${item.programId}`}>فتح التفاصيل</Link>}</details>}</div></li>)}</ol>;
}
export default function Activity() {
  const { activity } = useAdmin();
  const [query, setQuery] = useState(''); const [actor, setActor] = useState(''); const [action, setAction] = useState(''); const [entity, setEntity] = useState(''); const [source, setSource] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [page, setPage] = useState(1);
  const all = [...activity, ...sampleActivity].sort((a,b) => b.time.localeCompare(a.time));
  const rows = all.filter(item => (!actor || item.actor === actor) && (!action || item.action === action) && (!entity || item.entityType === entity) && (!source || (source === 'sample' ? item.sample : !item.sample)) && (!from || new Date(item.time) >= new Date(`${from}T00:00:00`)) && (!to || new Date(item.time) <= new Date(`${to}T23:59:59.999`)) && normalizeSearch(`${item.title} ${item.actor}`).includes(normalizeSearch(query)));
  const current = Math.min(page, Math.max(1, Math.ceil(rows.length / 10)));
  const filter = (setter: (value: string) => void) => (value: string) => { setter(value); setPage(1); };
  const reset = () => { setQuery(''); setActor(''); setAction(''); setEntity(''); setSource(''); setFrom(''); setTo(''); setPage(1); };
  return <><PageHeader title="سجل التعديلات" description="تتبّع ما تغيّر ومن عدّله، مع مقارنة القيم قبل التعديل وبعده." /><section className="adm-section adm-data-section"><div className="adm-data-heading"><div><h2>آخر النشاطات</h2><p>{activity.length} تعديلات في هذه الجلسة · {sampleActivity.length} أمثلة توضيحية</p></div><SearchField label="البحث في السجل" value={query} onChange={filter(setQuery)} /></div><div className="adm-filter-bar adm-activity-filters"><div className="adm-filter-group" role="group" aria-label="تصفية النشاط"><FilterSelect label="الموظف" value={actor} onChange={filter(setActor)} options={[...new Set(all.map(a => a.actor))].map(value => ({ value, label: value }))} /><FilterSelect label="الإجراء" value={action} onChange={filter(setAction)} options={Object.entries(actionLabels).map(([value,label]) => ({value,label}))} /><FilterSelect label="نوع العنصر" value={entity} onChange={filter(setEntity)} options={Object.entries(entityLabels).map(([value,label]) => ({value,label}))} /></div><div className="adm-filter-group adm-filter-dates" role="group" aria-label="المصدر والفترة"><FilterSelect label="المصدر" value={source} onChange={filter(setSource)} options={[{ value: 'session', label: 'هذه الجلسة' }, { value: 'sample', label: 'أمثلة توضيحية' }]} /><label className="adm-filter-select"><span>من تاريخ</span><input type="date" dir="ltr" value={from} max={to || undefined} onChange={e => filter(setFrom)(e.target.value)} /></label><label className="adm-filter-select"><span>إلى تاريخ</span><input type="date" dir="ltr" value={to} min={from || undefined} onChange={e => filter(setTo)(e.target.value)} /></label></div>{(query || actor || action || entity || source || from || to) && <button className="adm-text-link" onClick={reset}>مسح الفلاتر</button>}</div>{rows.length ? <ActivityRows items={rows.slice((current - 1) * 10, current * 10)} /> : <EmptyState title="لا توجد تعديلات مطابقة" description="ستظهر تعديلاتك المحفوظة هنا. يمكنك مسح الفلاتر لعرض جميع الأمثلة."><button className="adm-button" onClick={reset}>مسح الفلاتر</button></EmptyState>}<Pagination count={rows.length} page={current} onChange={setPage} /></section><p className="adm-source-note">الأمثلة ليست سجلًا فعليًا للمعهد. أحداث الجلسة مؤقتة ولا تُعد سجل تدقيق دائمًا.</p></>;
}
