import Link from 'next/link';
import type { ActivityResult } from '@/lib/admin/activity';
const actions: Record<string, string> = { create: 'إنشاء', update: 'تعديل', archive: 'أرشفة', restore: 'استعادة', delete: 'حذف', disable: 'إيقاف' };
const entities: Record<string, string> = { programs: 'برنامج', branches: 'فرع', program_offerings: 'عرض / تسعير', curriculum_items: 'مقرر', career_paths: 'مسار وظيفي' };
export default function HostedActivity({ result }: { result: ActivityResult }) {
  return <><header className="adm-page-heading"><div><h1>سجل التعديلات</h1><p>سجل التدقيق المحفوظ · أحدث 25 عملية في كل صفحة</p></div></header>
    {result.status !== 'ready' ? <section className="adm-section" role="alert"><h2>{result.status === 'invalid' ? 'رابط الصفحة غير صالح' : result.status === 'disabled' ? 'سجل التدقيق غير متاح في الوضع المحلي' : 'تعذر تحميل سجل التدقيق'}</h2><p>لم يتم عرض بيانات بديلة أو أمثلة.</p><Link className="adm-button" href="/admin/activity">العودة إلى أحدث النشاطات</Link></section>
      : <section className="adm-section"><h2>النشاطات المحفوظة</h2>{!result.items.length ? <p role="status">لا توجد نشاطات محفوظة في هذه الصفحة.</p> : <ol className="adm-timeline">{result.items.map(item => <li key={item.id} data-audit-id={item.id}><div className="adm-timeline-content" style={{ overflowWrap: 'anywhere', minWidth: 0 }}><h3>{actions[item.action] ?? item.action} · {item.label}</h3><p><time dateTime={item.time}>{new Date(item.time).toLocaleString('ar-SA', { timeZone: 'Asia/Riyadh', dateStyle: 'medium', timeStyle: 'medium' })}</time> · توقيت الرياض</p><p>{item.actor} · <bdi>{item.username}</bdi> · <bdi>{item.role}</bdi></p><p>{entities[item.entity] ?? item.entity} · <bdi>{item.entityId}</bdi></p><details><summary>معرّفات التدقيق والطلب</summary><p>التدقيق: <bdi>{item.id}</bdi></p><p>الطلب: <bdi>{item.requestId}</bdi></p></details></div></li>)}</ol>}<nav aria-label="صفحات سجل التدقيق"><Link className="adm-button" href="/admin/activity">الأحدث</Link>{result.nextCursor && <Link className="adm-button" rel="next" href={`/admin/activity?cursor=${encodeURIComponent(result.nextCursor)}`}>نشاطات أقدم</Link>}</nav></section>}</>;
}
