"use client";
import { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { mockUsers, roleLabels } from '@/lib/admin/mock-data';
import { normalizeSearch } from '@/lib/filters';
import { PageHeader, SearchField, StatusBadge } from './ui';
import { DataTable, FilterSelect } from './DataView';
export default function Users() {
  const [query, setQuery] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState('');
  const rows = mockUsers.filter(user => normalizeSearch(`${user.name} ${user.email}`).includes(normalizeSearch(query)) && (!role || user.role === role) && (!status || (status === 'active' ? user.active : !user.active)));
  const reset = () => { setQuery(''); setRole(''); setStatus(''); };
  return <><PageHeader title="المستخدمون" description="تصوّر مبدئي للأدوار ونطاق عمل الموظفين." /><div className="adm-inline-note"><ShieldCheck size={20} /><p>بيانات توضيحية فقط. هذه الأسماء والأدوار غير مرتبطة بحسابات الدخول أو الصلاحيات الفعلية.</p></div><section className="adm-section adm-data-section"><div className="adm-data-heading"><div><h2>فريق العمل التجريبي</h2><p>4 مستخدمين توضيحيين</p></div><SearchField label="البحث عن مستخدم" value={query} onChange={setQuery} /></div><div className="adm-filter-bar"><FilterSelect label="الدور" value={role} onChange={setRole} options={Object.entries(roleLabels).map(([value,label]) => ({value,label}))} /><FilterSelect label="الحالة" value={status} onChange={setStatus} options={[{value:'active',label:'نشط'},{value:'inactive',label:'غير نشط'}]} />{(query || role || status) && <button className="adm-text-link" onClick={reset}>مسح الفلاتر</button>}</div><DataTable rows={rows} emptyTitle="لا يوجد مستخدمون مطابقون" onReset={reset} columns={[{label:'المستخدم',render:u => <div className="adm-user-cell"><span className="adm-avatar" aria-hidden="true">{u.name.split(" ").slice(0, 2).map(part => part.charAt(0)).join(" ")}</span><div className="adm-cell-title"><strong>{u.name}</strong><small dir="ltr">{u.email}</small></div></div>},{label:'الدور',render:u => <div className="adm-cell-title"><span>{roleLabels[u.role]}</span></div>},{label:'نطاق العمل',render:u => u.scope},{label:'الحالة',render:u => <StatusBadge status={u.active ? 'active' : 'inactive'} />}]} /></section><section className="adm-section"><div className="adm-section-heading"><div><h2>دليل الأدوار المقترحة</h2><p>للمراجعة قبل تصميم الصلاحيات الفعلية.</p></div></div><dl className="adm-roles"><div><dt>مدير النظام</dt><dd>إدارة عامة للمحتوى والفروع والمستخدمين.</dd></div><div><dt>مدير المحتوى</dt><dd>تحرير البرامج والمقررات والصور وبيانات النشر.</dd></div><div><dt>مدير فرع</dt><dd>متابعة خيارات الدراسة والأسعار للفرع المخصص.</dd></div><div><dt>مشاهد</dt><dd>الاطلاع على البيانات دون تعديلها.</dd></div></dl></section></>;
}
